export const SET_DEMO = 'SET_DEMO'
export const SET_SYSSELECTED = 'SET_SYSSELECTED'
export const SET_SYSTREE = 'SET_SYSTREE'

export const SET_ECO_EVENT = 'SET_ECO_EVENT'
export const SET_ECO_EVENT_DATA = 'SET_ECO_EVENT_DATA'
