

export const INIT_WF_FORM_DESIGN_CONFIG = 'INIT_WF_FORM_DESIGN_CONFIG'
export const DELETE_WF_FORM_DESIGN_CONFIG = 'DELETE_WF_FORM_DESIGN_CONFIG'

export const SET_WF_FORM_DESIGN_CONFIG = 'SET_WF_FORM_DESIGN_CONFIG' 
export const SET_WF_FORM_DESIGN_CONFIG_CHANGE = 'SET_WF_FORM_DESIGN_CONFIG_CHANGE' 

export const SET_WF_FORM_DESIGN_CONFIG2 = 'SET_WF_FORM_DESIGN_CONFIG2' 
export const SET_WF_FORM_DESIGN_CONFIG_CHANGE2 = 'SET_WF_FORM_DESIGN_CONFIG_CHANGE2' 

export const SET_FORM_DESIGN_MODEL_AND_VIEW = 'SET_FORM_DESIGN_MODEL_AND_VIEW' 
export const DELETE_FORM_DESIGN_MODEL_AND_VIEW = 'DELETE_FORM_DESIGN_MODEL_AND_VIEW'

export const DELETE_WF_GRID_DESIGN_CONFIG = 'DELETE_WF_GRID_DESIGN_CONFIG'
export const SET_WF_GRID_DESIGN_CONFIG = 'SET_WF_GRID_DESIGN_CONFIG' 
export const SET_WF_GRID_DESIGN_CONFIG_CHANGE = 'SET_WF_GRID_DESIGN_CONFIG_CHANGE'