export const SET_LOGIN_USER = 'SET_LOGIN_USER'
export const SET_MENU_TAB_CLICK = 'SET_MENU_TAB_CLICK'
export const SET_MENU_TAB_ARRAY = 'SET_MENU_TAB_ARRAY'
export const SET_TOGGLE_MENU = 'SET_TOGGLE_MENU'
export const SET_TEMP_OBJ = 'SET_TEMP_OBJ'
export const DELETE_TEMP_OBJ = 'DELETE_TEMP_OBJ'

export const SET_ECO_SETTING_OBJ = 'SET_ECO_SETTING_OBJ'