export const SET_DEMO = 'SET_DEMO'
export const SET_BASE_DATA_OBJ= 'SET_BASE_DATA_OBJ'

export const SET_ECO_EVENT = 'SET_ECO_EVENT'
export const SET_ECO_EVENT_DATA = 'SET_ECO_EVENT_DATA'

export const SET_STATUS_LIST = 'SET_STATUS_LIST'
export const SET_IMPORTANTTYPE_LIST ='SET_IMPORTANTTYPE_LIST' 
export const SET_REGULATORYCOMPLIANCE_LIST = 'SET_REGULATORYCOMPLIANCE_LIST'

export const SET_INIT_ROLE = 'SET_INIT_ROLE'