export const SET_DEMO = 'SET_DEMO'
export const SET_WF_KV_MAP = 'SET_WF_KV_MAP'
export const SET_WF_PAGE_EVENTS = 'SET_WF_PAGE_EVENTS' 
export const SET_WF_HAND_SIGNS_MAP = 'SET_WF_HAND_SIGNS_MAP' 

export const INIT_WF_FORM_DESIGN_CONFIG = 'INIT_WF_FORM_DESIGN_CONFIG'
export const DELETE_WF_FORM_DESIGN_CONFIG = 'DELETE_WF_FORM_DESIGN_CONFIG'

export const SET_WF_FORM_DESIGN_CONFIG = 'SET_WF_FORM_DESIGN_CONFIG' 
export const SET_WF_FORM_DESIGN_CONFIG_CHANGE = 'SET_WF_FORM_DESIGN_CONFIG_CHANGE' 

export const SET_WF_FORM_DESIGN_CONFIG2 = 'SET_WF_FORM_DESIGN_CONFIG2' 
export const SET_WF_FORM_DESIGN_CONFIG_CHANGE2 = 'SET_WF_FORM_DESIGN_CONFIG_CHANGE2' 


export const INIT_WF_GRID_DESIGN_CONFIG = 'INIT_WF_GRID_DESIGN_CONFIG'
export const DELETE_WF_GRID_DESIGN_CONFIG = 'DELETE_WF_GRID_DESIGN_CONFIG'

export const SET_WF_GRID_DESIGN_CONFIG = 'SET_WF_GRID_DESIGN_CONFIG' 
export const SET_WF_GRID_DESIGN_CONFIG_CHANGE = 'SET_WF_GRID_DESIGN_CONFIG_CHANGE'

export const SET_DIRECTION_DATA= 'SET_DIRECTION_DATA'
export const SET_OPERATE_ID= 'SET_OPERATE_ID' 

export const SET_PUBLIC_SETTING_UNION = 'SET_PUBLIC_SETTING_UNION' 
export const SET_VIEW_TAB_ACTIVE_KEY = 'SET_VIEW_TAB_ACTIVE_KEY' 

export const SET_FORMULA_SETTING = 'SET_FORMULA_SETTING' //公式
export const SET_FORMULA_SETTING_CHANGE = 'SET_FORMULA_SETTING_CHANGE' //公式
export const SET_FORMULA_FORM_DATA = 'SET_FORMULA_FORM_DATA' //公式表单数据
export const DELETA_ALL_FORMULA_SETTING = 'DELETA_ALL_FORMULA_SETTING' //公式表单数据
