export const SET_DEMO = 'SET_DEMO'
export const SET_TERM_TYPE = 'SET_TERM_TYPE'
export const SET_PROFESSION = 'SET_PROFESSION'
export const SET_TEMP_OBJ = 'SET_TEMP_OBJ'
export const DELETE_TEMP_OBJ = 'DELETE_TEMP_OBJ'
export const SET_BTNROLE_MAP = 'SET_BTNROLE_MAP'
